(function(){
'use strict';
var names='WLD ORO WDD ORB WNB XAU MINI HUMN ORBID GASW WUSD BETA EYE PAY APP CHAIN SCAN WBRG FEE DAPP SPOT POOL FLOW VAULT HUB TILE NODE NOVA CRED LENS RING MAP RISK SAFE IDX DATA CORE WAVE SEED DUST'.split(' ');
var risk=['healthy','healthy','thin-liquidity','healthy','thin-liquidity','healthy','new-or-volatile','healthy','thin-liquidity','new-or-volatile','healthy','thin-liquidity','healthy','thin-liquidity','new-or-volatile','healthy','thin-liquidity','healthy','unknown','new-or-volatile','healthy','thin-liquidity','new-or-volatile','healthy','thin-liquidity','healthy','thin-liquidity','new-or-volatile','unknown','healthy','new-or-volatile','healthy','thin-liquidity','healthy','unknown','stale','thin-liquidity','new-or-volatile','thin-liquidity','stale'];
var data=names.map(function(s,i){var size=40-i;var vol=Math.round(12000000*Math.pow(size/40,2.15)+70000);var liq=Math.round(8000000*Math.pow(size/40,2.55)+18000);var ch=((i*37)%70)-24+(i%5===0?8:0);return{id:'t'+i,symbol:s,name:s+' demo',volume24h:vol,liquidityUsd:liq,change24h:ch,fdv:vol*3.4,riskState:risk[i],status:risk[i]==='stale'?'stale':'demo'};});
var state={mode:'market',nodes:[],selected:'t0',scale:1,tx:0,ty:0,drag:false,moved:false,start:null};
var el={};
var modeDef={market:{label:'Market',desc:'Area = 24h volume. Color = 24h price change.',area:function(t){return t.volume24h},rank:'24h volume'},liquidity:{label:'Liquidity',desc:'Area = liquidity. Color = liquidity condition.',area:function(t){return t.liquidityUsd},rank:'liquidity'},risk:{label:'Risk',desc:'Area = liquidity. Color = risk state. Risk is not a safety score.',area:function(t){return t.liquidityUsd},rank:'liquidity'}};
function boot(){el.v=$('heatmapViewport');el.c=$('heatmapTiles');el.o=$('heatmapOverlay');el.cx=el.c.getContext('2d');el.ox=el.o.getContext('2d');el.sel=$('selectedDetail');el.rank=$('miniRanking');el.desc=$('modeDescription');el.status=$('statusMode');el.legend=$('modeLegend');document.querySelectorAll('.mode-btn').forEach(function(b){b.onclick=function(){state.mode=b.dataset.mode;document.querySelectorAll('.mode-btn').forEach(function(x){x.classList.toggle('is-active',x===b)});layout();};});$('resetZoom').onclick=function(){state.scale=1;state.tx=0;state.ty=0;draw();};var mt=$('mobileMapToggle');mt.onclick=function(){el.v.classList.toggle('is-move-mode');mt.textContent=el.v.classList.contains('is-move-mode')?'Back to scroll':'Control map';$('interactionHint').textContent=el.v.classList.contains('is-move-mode')?'Pan map':'Page scroll · Tap tiles';};el.v.addEventListener('wheel',wheel,{passive:false});el.v.addEventListener('dblclick',dbl);el.v.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);new ResizeObserver(function(){requestAnimationFrame(layout)}).observe(el.v);layout();}
function $(id){return document.getElementById(id)}
function layout(){var r=el.v.getBoundingClientRect(),w=Math.max(320,Math.floor(r.width)),h=Math.max(320,Math.floor(r.height));setup(el.c,w,h);setup(el.o,w,h);var m=modeDef[state.mode];var items=data.map(function(t){return{id:t.id,label:t.symbol,areaValue:m.area(t),meta:t};}).filter(function(x){return x.areaValue>0});el.desc.textContent=m.desc;el.status.textContent=m.label;el.legend.innerHTML=legend();state.nodes=treemap(items,0,0,w,h).map(function(n,i){n.rank=i+1;return n});state.scale=1;state.tx=0;state.ty=0;renderSelected();renderRanking();draw();}
function setup(c,w,h){var d=window.devicePixelRatio||1;c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';c.getContext('2d').setTransform(d,0,0,d,0,0);}
function treemap(items,x,y,w,h){items=items.slice().sort(function(a,b){return b.areaValue-a.areaValue});var total=items.reduce(function(s,i){return s+i.areaValue},0);return split(items,x,y,w,h,total);}
function split(items,x,y,w,h,total){if(items.length<2)return items[0]?[Object.assign({},items[0],{x:x,y:y,w:w,h:h})]:[];var a=[],b=[],sum=0;for(var i=0;i<items.length;i++){if(sum<total/2||!a.length){a.push(items[i]);sum+=items[i].areaValue}else b.push(items[i]);}var rest=total-sum;if(w>=h){var aw=w*sum/total;return split(a,x,y,aw,h,sum).concat(split(b,x+aw,y,w-aw,h,rest));}var ah=h*sum/total;return split(a,x,y,w,ah,sum).concat(split(b,x,y+ah,w,h-ah,rest));}
function draw(){drawTiles();drawOverlay();}
function drawTiles(){var c=el.cx,w=el.c.clientWidth,h=el.c.clientHeight;c.clearRect(0,0,w,h);c.fillStyle='#f7f7f7';c.fillRect(0,0,w,h);state.nodes.forEach(function(n){var r=rect(n),p=Math.min(4,Math.max(1,Math.min(r.w,r.h)*.04));c.fillStyle=color(n.meta);c.fillRect(r.x+p,r.y+p,Math.max(0,r.w-p*2),Math.max(0,r.h-p*2));c.strokeStyle='rgba(255,255,255,.85)';c.strokeRect(r.x+p,r.y+p,Math.max(0,r.w-p*2),Math.max(0,r.h-p*2));label(c,n,r,p);});}
function label(c,n,r,p){var area=r.w*r.h,side=Math.min(r.w,r.h);if(side<26||area<1200)return;c.save();c.beginPath();c.rect(r.x+p,r.y+p,Math.max(0,r.w-p*2),Math.max(0,r.h-p*2));c.clip();c.fillStyle=textColor(color(n.meta));c.font='800 13px system-ui';c.fillText(n.meta.symbol,r.x+p+8,r.y+p+18,Math.max(20,r.w-18));if(side>52&&area>4200){c.font='700 11px system-ui';c.fillText(state.mode==='market'?pct(n.meta.change24h):usd(n.areaValue),r.x+p+8,r.y+p+34,Math.max(20,r.w-18));}c.restore();}
function drawOverlay(){var c=el.ox,w=el.o.clientWidth,h=el.o.clientHeight;c.clearRect(0,0,w,h);var n=state.nodes.find(function(x){return x.id===state.selected});if(!n)return;var r=rect(n);c.strokeStyle='#111';c.lineWidth=3;c.strokeRect(r.x+3,r.y+3,Math.max(0,r.w-6),Math.max(0,r.h-6));}
function rect(n){return{x:n.x*state.scale+state.tx,y:n.y*state.scale+state.ty,w:n.w*state.scale,h:n.h*state.scale};}
function hit(e){var b=el.v.getBoundingClientRect(),x=(e.clientX-b.left-state.tx)/state.scale,y=(e.clientY-b.top-state.ty)/state.scale;for(var i=state.nodes.length-1;i>=0;i--){var n=state.nodes[i];if(x>=n.x&&x<=n.x+n.w&&y>=n.y&&y<=n.y+n.h)return n;}return null;}
function wheel(e){if(!(e.ctrlKey||e.altKey||e.metaKey))return;e.preventDefault();zoom(e,e.deltaY<0?1.12:.89);}
function dbl(e){e.preventDefault();zoom(e,e.shiftKey?.72:1.45);}
function zoom(e,f){var b=el.v.getBoundingClientRect(),sx=e.clientX-b.left,sy=e.clientY-b.top,old=state.scale,ns=Math.min(5,Math.max(.75,old*f)),wx=(sx-state.tx)/old,wy=(sy-state.ty)/old;state.scale=ns;state.tx=sx-wx*ns;state.ty=sy-wy*ns;draw();}
function down(e){state.drag=true;state.moved=false;state.start={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};}
function move(e){if(!state.drag)return;var dx=e.clientX-state.start.x,dy=e.clientY-state.start.y;if(Math.hypot(dx,dy)>6)state.moved=true;if(state.moved){state.tx=state.start.tx+dx;state.ty=state.start.ty+dy;draw();}}
function up(e){if(!state.drag)return;if(!state.moved){var n=hit(e);if(n){state.selected=n.id;renderSelected();drawOverlay();}}state.drag=false;state.moved=false;}
function renderSelected(){var n=state.nodes.find(function(x){return x.id===state.selected})||state.nodes[0];if(!n)return;var t=n.meta;el.sel.innerHTML='<div><div class="selected-symbol">'+esc(t.symbol)+'</div><div class="selected-name">'+esc(t.name)+'</div></div>'+row('24h change',pct(t.change24h))+row('24h volume',usd(t.volume24h))+row('Liquidity',usd(t.liquidityUsd))+row('FDV / cap',usd(t.fdv))+row('Risk state','<span class="risk-label risk-'+esc(t.riskState)+'">'+esc(t.riskState)+'</span>')+row('Data status',esc(t.status))+'<div class="detail-actions"><a class="btn" href="/world-chain/sell-impact/">Open in Sell Impact</a><a class="btn secondary" href="/world-chain/ecosystem/?q='+encodeURIComponent(t.symbol)+'">Open in Ecosystem</a></div>';}
function renderRanking(){var m=modeDef[state.mode];el.rank.innerHTML=data.slice().map(function(t){return{t:t,v:m.area(t)}}).sort(function(a,b){return b.v-a.v}).slice(0,12).map(function(e,i){return'<div class="ranking-row"><div class="ranking-rank">#'+(i+1)+'</div><div><div class="ranking-symbol">'+esc(e.t.symbol)+'</div><div class="ranking-sub">'+esc(e.t.name)+' · '+esc(e.t.riskState)+'</div></div><div class="ranking-value">'+usd(e.v)+'</div></div>';}).join('');}
function row(a,b){return'<div class="detail-row"><span>'+a+'</span><strong>'+b+'</strong></div>'}
function color(t){if(state.mode==='risk')return riskColor(t.riskState);if(state.mode==='liquidity')return t.liquidityUsd>1000000?'#2f7d46':t.liquidityUsd>120000?'#b47a23':'#a94442';return changeColor(t.change24h);}
function changeColor(v){if(Math.abs(v)<.5)return'#b6b6b6';return v>0?'#2f7d46':'#a94442'}
function riskColor(r){return r==='healthy'?'#2f7d46':r==='thin-liquidity'?'#b47a23':r==='new-or-volatile'?'#9a6b1f':r==='stale'?'#777':'#999'}
function legend(){var list=state.mode==='market'?[['Positive','#2f7d46'],['Flat','#b6b6b6'],['Negative','#a94442']]:state.mode==='liquidity'?[['Strong','#2f7d46'],['Thin','#b47a23'],['Weak','#a94442']]:[['Observed','#2f7d46'],['Caution','#b47a23'],['Unknown/stale','#777']];return list.map(function(x){return'<span class="legend-item"><span class="legend-dot" style="background:'+x[1]+'"></span>'+x[0]+'</span>';}).join('')}
function textColor(c){return c==='#2f7d46'||c==='#a94442'||c==='#9a6b1f'||c==='#777'?'#fff':'#111'}
function usd(v){return v>=1e6?'$'+(v/1e6).toFixed(2)+'M':v>=1e3?'$'+(v/1e3).toFixed(1)+'K':'$'+v.toFixed(2)}
function pct(v){return(v>0?'+':'')+v.toFixed(1)+'%'}
function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
